ALTER TABLE "User" ADD COLUMN "passwordHash" VARCHAR(255) NOT NULL DEFAULT '$2b$12$fVca8NteijNmomvAHju0GuSQRqh.U7yEFHA5Ef6GQLEikFbrThJJy';

ALTER TABLE "User" ALTER COLUMN "passwordHash" DROP DEFAULT;